### ISSUE TITLE
tl import fails for getting a MBTiles extract from http source

### ISSUE THREAD

**Issue by hallahan** [mojodna/tilelive-http#11]
Here's the command I'm attempting:

```
tl copy -z 13 -Z 21 -b '-77.059908 38.881145 -77.013903 38.912207' 'http://c.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png' mbtiles://./hot-summit-dc.mbtiles
```

And here's the errors I'm getting:

```
Error: Upstream error:503
    at Request._callback (/usr/local/lib/node_modules/tilelive-http/index.js:61:15)
    at Request.self.callback (/usr/local/lib/node_modules/tilelive-http/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/tilelive-http/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/tilelive-http/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

and

```
Error: getaddrinfo ENOTFOUND
   at errnoException (dns.js:37:11)
   at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by mojodna** [comment]
Much better after v0.6.1
